version: 0.2
phases:

  build:
    commands:
      - javac src/sample/Hello.java
      - java -cp src sample.Hello
      - cd src
      - jar cf Hello.jar sample/Hello.class 

artifacts:
  discard-paths: yes
  files:
    - src/Hello.jar
  name: $CODEBUILD_BUILD_NUMBER